### ISSUE TITLE
[BUG]: deepFindPathToProperty() throws TypeError if graphql response field is null

### ISSUE THREAD

**Issue by stergion** [octokit/plugin-paginate-graphql.js#58]
### What happened?

Some times a graphql response fields have value null. This causes currentValue.hasOwnProperty(searchProp) to throw `TypeError: Cannot read properties of null (reading 'hasOwnProperty')` error. 

<details>
<summary>Minimal Reproducible Example</summary>

```javascript
import nock from 'nock';
import { Octokit } from "octokit";
import { paginateGraphql } from "@octokit/plugin-paginate-graphql";

const MyOctokit = Octokit.plugin(paginateGraphql);
const octokit = new MyOctokit({ auth: "secret123" });


const myQuery = `{ 
    query {
      user(login: "stergion") {
        name
        login
        contributionsCollection {
          earliestRestrictedContributionDate
          latestRestrictedContributionDate
        }
      }
    }
  }`;

nock.disableNetConnect();
nock('https://api.github.com')
  .post('/graphql', '{"query":"{ \\n    query {\\n      user(login: \\"stergion\\") {\\n        name\\n        login\\n        contributionsCollection {\\n          earliestRestrictedContributionDate\\n          latestRestrictedContributionDate\\n        }\\n      }\\n    }\\n  }"}')
  .reply(200, {
    "data": {
      "user": {
        "name": null,
        "login": "stergion",
        "contributionsCollection": {
          "earliestRestrictedContributionDate": "2022-02-13",
          "latestRestrictedContributionDate": "2023-02-14"
        }
      }
    }
  });

// const response = await octokit.graphql.paginate(myQuery);

try {
  const response = await octokit.graphql.paginate(myQuery);
  console.log(response);
} catch (error) {
  console.log(`${error.name}: ${error.status}`);
  console.log(error);
}
```

</details>

### Versions

@octokit/plugin-paginate-graphql@2.0.1
octokit@2.0.14
Node v16.17.0

### Relevant log output

```
TypeError: undefined
TypeError: Cannot read properties of null (reading 'hasOwnProperty')
    at deepFindPathToProperty (/home/mre/node_modules/@octokit/plugin-paginate-graphql/dist-node/index.js:52:22)
    at deepFindPathToProperty (/home/mre/node_modules/@octokit/plugin-paginate-graphql/dist-node/index.js:57:22)
    at findPaginatedResourcePath (/home/mre/node_modules/@octokit/plugin-paginate-graphql/dist-node/index.js:38:33)
    at extractPageInfos (/home/mre/node_modules/@octokit/plugin-paginate-graphql/dist-node/index.js:94:24)
    at Object.next (/home/mre/node_modules/@octokit/plugin-paginate-graphql/dist-node/index.js:122:35)
    at async Function.paginate (/home/mre/node_modules/@octokit/plugin-paginate-graphql/dist-node/index.js:178:22)
    at async file:///home/rme/index.mjs:41:20
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stergion** [comment]
Added a minimal reproducible example and the corresponding log output.

**Comment by nickfloyd** [comment]
I had a quick look at this. [Here](https://github.com/octokit/plugin-paginate-graphql.js/blob/main/src/object-helpers.ts#L26) is a good place to start - the conditional on line 26 could be predicated by a null check on `currentValue` | this is a common issue in .NET as well around nullable types and `hasValue`.

However, I’m not 100% clear on what side effects that might cause so well need some coverage on this scenario as well - just to ensure this change is doing what is expected.

**Comment by stergion** [comment]
That's what I also thought. My suggested PR #59 adds a null check.

**Comment by karpikpl** [comment]
I'm getting same issue when I try to do a query without enough permissions.
```js
    const iterator = await this.graphql.paginate.iterator(query, { ent })
    let page_check_done = false
      for await (const result of iterator) {
        const orgs = result.enterprise.organizations.nodes
```
it blows up with:
> TypeError: Cannot read properties of null (reading 'hasOwnProperty')
    at deepFindPathToProperty (file:///home/projects/gh-users-action/node_modules/@octokit/plugin-paginate-graphql/dist-bundle/index.js:49:22)

is there a chance for a fix?
